Crud api
AleksandarSavic95/php-api pull request #5
Opened 2018-04-26 11:23 UTC by AleksandarSavic95

2018-04-26 13:25 UTC, calico-anne requested changes

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        return TodoItem::all();
Je l' si razmisljao da ti mozda ne trebaju bas svi ToDo-ovi i od svih korisnika? :D Moras po ID-ju user-a uzimati sta ti treba..ovo ce uvek vracati svacije.

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        // \Log::info($request);
Visak :D

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        return response()->json($todoitem, 201);
Ako se ne varam, ovo ti je visak. Laravel ce da ti handle-a konverziju u `.json`. 
Dovoljno je da kazes
`return $todoItem;`

Ili jos bolje, oneliner
`return TodoItem::create($request->all());`

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        $todoitem = TodoItem::create($request->all());
Koristi `camelCase`

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        return response()->json($todoitem, 200);
Isto vazi kao i gore. :D

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +    public function delete(TodoItem $todoitem)
Obicno se za `delete` i `update` kao drugi parametar prima `id`, ne ceo item.

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        return response()->json(null, 204);
Isto kao i gore. :D

2018-04-26 13:25 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +    public function update(Request $request, TodoItem $todoitem)
Napisala sam ispod, ovde bi trebalo da primis `id`. :D

2018-04-27 08:53 UTC, AleksandarSavic95 commented on app/Http/Controllers/TodoItemController.php
> +    public function update(Request $request, TodoItem $todoitem)
https://www.toptal.com/laravel/restful-laravel-api-tutorial
Implicit route model binding :))

2018-04-27 11:47 UTC, calico-anne requested changes

2018-04-27 11:47 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        // $userId = Auth::User()->id; // Auth::user() ?
Komentare brisiiii

2018-04-27 11:47 UTC, volkova229 commented on app/Http/Controllers/TodoItemController.php
> +        return TodoItem::create(array_merge($request->all(), ['user_id' => 1]));
`['user_id' => Auth::id()]`

2018-04-27 12:17 UTC, calico-anne approved these changes

2018-04-27 12:17 UTC, merged